name: Issue Solver

on:
  issues:
    types: [opened]
  workflow_dispatch:  # Allow manual triggering of the action

jobs:
  solve_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install openai PyGithub

      - name: Solve issues with GPT-4
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/issue_solver.py
